/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/pablo/git/programitas-algebraI/nim/nimcache/factorizar.o /home/pablo/git/programitas-algebraI/nim/nimcache/factorizar.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef linux
typedef struct TY_8Np6tlClE5az1CyqZdN19bQ TY_8Np6tlClE5az1CyqZdN19bQ;
typedef struct TY_1v9bKyksXWMsm0vNwmZ4EuQ TY_1v9bKyksXWMsm0vNwmZ4EuQ;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct Cellseq_Axo1XVm9aaQueTOldv8le5w Cellseq_Axo1XVm9aaQueTOldv8le5w;
typedef struct Gcheap_1TRH1TZMaVZTnLNcIHuNFQ Gcheap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct Gcstack_7fytPA5bBsob6See21YMRA Gcstack_7fytPA5bBsob6See21YMRA;
typedef struct Memregion_x81NhDv59b8ercDZ9bi85jyg Memregion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct Smallchunk_tXn60W2f8h3jgAYdEmy5NQ Smallchunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct Llchunk_XsENErzHIZV9bhvyJx56wGw Llchunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct Bigchunk_Rv9c70Uhp2TytkX7eH78qEg Bigchunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct Intset_EZObFrE3NC9bIb3YMkY9crZA Intset_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct Avlnode_IaqjtwKhxLEpvDS9bct9blEw Avlnode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct Gcstat_0RwLoVBHZPfUAcLczmfQAg Gcstat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct Cellset_jG87P0AI9aZtss9ccTYBIISQ Cellset_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct Pagedesc_fublkgIY4LG3mT51LU2WHg Pagedesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Basechunk_Sdq7WpT6qAH858F5ZEdG3w Basechunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct Freecell_u6M5LHprqzkn9axr04yg9bGQ Freecell_u6M5LHprqzkn9axr04yg9bGQ;
struct TY_1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, TY_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* TY_24KAM9afIUgUaqBaEBB6r9bg[3];
typedef NimStringDesc* TY_nHXaesL0DJZHyVS07ARPRA[1];
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  Cellseq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  Intset_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
struct  Memregion_x81NhDv59b8ercDZ9bi85jyg  {
NI minlargeobj;
NI maxlargeobj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freesmallchunks;
Llchunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* freechunkslist;
Intset_EZObFrE3NC9bIb3YMkY9crZA chunkstarts;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* root;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* last;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* freeavlnodes;
NIM_BOOL locked;
NIM_BOOL blockchunksizeincrease;
NI nextchunksize;
};
struct  Gcstat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
Pagedesc_fublkgIY4LG3mT51LU2WHg* head;
Pagedesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  Gcheap_1TRH1TZMaVZTnLNcIHuNFQ  {
Gcstack_7fytPA5bBsob6See21YMRA* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq_Axo1XVm9aaQueTOldv8le5w zct;
Cellseq_Axo1XVm9aaQueTOldv8le5w decstack;
Cellseq_Axo1XVm9aaQueTOldv8le5w tempstack;
NI recgclock;
Memregion_x81NhDv59b8ercDZ9bi85jyg region;
Gcstat_0RwLoVBHZPfUAcLczmfQAg stat;
Cellset_jG87P0AI9aZtss9ccTYBIISQ marked;
Cellseq_Axo1XVm9aaQueTOldv8le5w additionalroots;
};
struct  Gcstack_7fytPA5bBsob6See21YMRA  {
Gcstack_7fytPA5bBsob6See21YMRA* prev;
Gcstack_7fytPA5bBsob6See21YMRA* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk_tXn60W2f8h3jgAYdEmy5NQ  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* next;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
Freecell_u6M5LHprqzkn9axr04yg9bGQ* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
Llchunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  Bigchunk_Rv9c70Uhp2TytkX7eH78qEg  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* next;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NI align;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef Avlnode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  Avlnode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc_fublkgIY4LG3mT51LU2WHg  {
Pagedesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  Freecell_u6M5LHprqzkn9axr04yg9bGQ  {
Freecell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zerofield;
};
struct TY_8Np6tlClE5az1CyqZdN19bQ {
  TGenericSeq Sup;
  TY_1v9bKyksXWMsm0vNwmZ4EuQ data[SEQ_DECL_SIZE];
};
static N_NIMCALL(void, Marker_TY_8Np6tlClE5az1CyqZdN19bQ)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d0, NI op0);
static N_NIMCALL(void, T_Cp3TFfIqQo1kvLGjPaz3VA_3)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(TY_T4eqaYlFJYZUv9aG9b1TV0bQ markerproc0);
static N_NIMCALL(void, T_Cp3TFfIqQo1kvLGjPaz3VA_4)(void);
N_NIMCALL(TY_8Np6tlClE5az1CyqZdN19bQ*, newseq_K08h1uqfk9adgihUsXGrGjQ)(NI len0);
N_NIMCALL(TY_8Np6tlClE5az1CyqZdN19bQ*, factorize_j9cKmPt8LHHuq9awLaHwEVUQ)(NI n00);
static N_INLINE(NI, modInt)(NI a0, NI b0);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, divInt)(NI a0, NI b0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq0, NI elemsize0);
N_NIMCALL(void, genericSeqAssign)(void* dest0, void* src_qi9cfsBnd42r9a9cpCLO10jow, TNimType* mt0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, writeline_rBQVO3cm3BhnA9aEFD7PG6Qfactorizar)(FILE* f0, NimStringDesc** x0, NI x0Len0);
N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f0, NimStringDesc* s0);
N_NIMCALL(void, prettyfactorization_9bKmnnny2qFitg44gLo9c16g)(TY_8Np6tlClE5az1CyqZdN19bQ* factorsseq0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(void, write_OG3BP9aaTiau0tBdonibGTg)(FILE* f0, NimStringDesc** a0, NI a0Len0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src0);
N_NIMCALL(void, failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg0);
N_NIMCALL(NimStringDesc*, readline_fPRnXwDTqtynUYGl4OixAg)(FILE* f0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0);
static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NOINLINE(void, addzct_fCDI7oO1NNVXXURtxSzsRw)(Cellseq_Axo1XVm9aaQueTOldv8le5w* s0, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s0);
static N_INLINE(void, initStackBottomWith)(void* locals0);
N_NOINLINE(void, setStackBottom)(void* thestackbottom0);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, factorizarDatInit000)(void);
TY_8Np6tlClE5az1CyqZdN19bQ* factorsseq_AN3HbB3vvESZC0wn9chyo7A;
TNimType NTI_1v9bKyksXWMsm0vNwmZ4EuQ;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA;
TNimType NTI_8Np6tlClE5az1CyqZdN19bQ;
NimStringDesc* s_YwfZBocky9bQVtUWcozCTrg;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg;
NI numero_0pcR4K1CUgJaGm61CY7rgg;
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern Gcheap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(T_Cp3TFfIqQo1kvLGjPaz3VA_8, "=", 1);
STRING_LITERAL(T_Cp3TFfIqQo1kvLGjPaz3VA_9, "*", 1);
STRING_LITERAL(T_Cp3TFfIqQo1kvLGjPaz3VA_11, "\012", 1);
STRING_LITERAL(T_Cp3TFfIqQo1kvLGjPaz3VA_12, "1", 1);
STRING_LITERAL(T_Cp3TFfIqQo1kvLGjPaz3VA_13, "^", 1);
STRING_LITERAL(T_Cp3TFfIqQo1kvLGjPaz3VA_15, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(T_Cp3TFfIqQo1kvLGjPaz3VA_17, "", 0);
NIM_CONST TY_nHXaesL0DJZHyVS07ARPRA T_Cp3TFfIqQo1kvLGjPaz3VA_16 = {((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_17)}
;
STRING_LITERAL(T_Cp3TFfIqQo1kvLGjPaz3VA_18, "Ingrese un n\303\272mero para factorizar", 34);
STRING_LITERAL(T_Cp3TFfIqQo1kvLGjPaz3VA_19, "Usted ingres\303\263 el n\303\272mero ", 26);
static N_NIMCALL(void, Marker_TY_8Np6tlClE5az1CyqZdN19bQ)(void* p, NI op) {
	TY_8Np6tlClE5az1CyqZdN19bQ* a;
	NI LOC1;
	a = (TY_8Np6tlClE5az1CyqZdN19bQ*)p;
	LOC1 = (NI)0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	}
}
static N_NIMCALL(void, T_Cp3TFfIqQo1kvLGjPaz3VA_3)(void) {
	nimGCvisit((void*)factorsseq_AN3HbB3vvESZC0wn9chyo7A, 0);
}
static N_NIMCALL(void, T_Cp3TFfIqQo1kvLGjPaz3VA_4)(void) {
	nimGCvisit((void*)s_YwfZBocky9bQVtUWcozCTrg, 0);
}

static N_INLINE(NI, modInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	result0 = (NI)(a0 % b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, divInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b0 == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result0 = (NI)(a0 / b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(TY_8Np6tlClE5az1CyqZdN19bQ*, factorize_j9cKmPt8LHHuq9awLaHwEVUQ)(NI n00) {
	TY_8Np6tlClE5az1CyqZdN19bQ* result0;
	NI n0;
	NI m0;
	NI d0;
	NI e0;
	TY_1v9bKyksXWMsm0vNwmZ4EuQ p0;
	TY_8Np6tlClE5az1CyqZdN19bQ* factorsseq0;
	nimfr("factorize", "factorizar.nim")
{	result0 = (TY_8Np6tlClE5az1CyqZdN19bQ*)0;
	n0 = (NI)0;
	m0 = (NI)0;
	d0 = (NI)0;
	e0 = (NI)0;
	memset((void*)(&p0), 0, sizeof(p0));
	nimln(29, "factorizar.nim");
	factorsseq0 = newseq_K08h1uqfk9adgihUsXGrGjQ(((NI) 0));
	nimln(32, "factorizar.nim");
	n0 = n00;
	{
		NI d_C1849bXpr8Pdh29cb9aQLE3vA;
		NI res_9abQT5z83KHZNmrNbTymbXg;
		d_C1849bXpr8Pdh29cb9aQLE3vA = (NI)0;
		nimln(1908, "system.nim");
		res_9abQT5z83KHZNmrNbTymbXg = ((NI) 2);
		{
			nimln(1909, "system.nim");
			while (1) {
				NI T_Cp3TFfIqQo1kvLGjPaz3VA_10;
				nimln(1908, "system.nim");
				if (!(res_9abQT5z83KHZNmrNbTymbXg <= n0)) goto LA3;
				nimln(1910, "system.nim");
				d_C1849bXpr8Pdh29cb9aQLE3vA = res_9abQT5z83KHZNmrNbTymbXg;
				nimln(34, "factorizar.nim");
				e0 = ((NI) 0);
				{
					nimln(35, "factorizar.nim");
					while (1) {
						NI T_Cp3TFfIqQo1kvLGjPaz3VA_5;
						NI T_Cp3TFfIqQo1kvLGjPaz3VA_6;
						NI T_Cp3TFfIqQo1kvLGjPaz3VA_7;
						NimStringDesc* LOC6;
						NimStringDesc* LOC7;
						NimStringDesc* LOC8;
						T_Cp3TFfIqQo1kvLGjPaz3VA_5 = modInt(n0, d_C1849bXpr8Pdh29cb9aQLE3vA);
						if (!((NI)(T_Cp3TFfIqQo1kvLGjPaz3VA_5) == ((NI) 0))) goto LA5;
						nimln(36, "factorizar.nim");
						T_Cp3TFfIqQo1kvLGjPaz3VA_6 = addInt(e0, ((NI) 1));
						e0 = (NI)(T_Cp3TFfIqQo1kvLGjPaz3VA_6);
						nimln(37, "factorizar.nim");
						T_Cp3TFfIqQo1kvLGjPaz3VA_7 = divInt(n0, d_C1849bXpr8Pdh29cb9aQLE3vA);
						m0 = (NI)(T_Cp3TFfIqQo1kvLGjPaz3VA_7);
						nimln(38, "factorizar.nim");
						LOC6 = (NimStringDesc*)0;
						LOC6 = nimIntToStr(n0);
						LOC7 = (NimStringDesc*)0;
						LOC7 = nimIntToStr(m0);
						LOC8 = (NimStringDesc*)0;
						LOC8 = nimIntToStr(d_C1849bXpr8Pdh29cb9aQLE3vA);
						printf("%s%s%s%s%s\012", LOC6? (LOC6)->data:"nil", ((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_8)? (((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_8))->data:"nil", LOC7? (LOC7)->data:"nil", ((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_9)? (((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_9))->data:"nil", LOC8? (LOC8)->data:"nil");
						fflush(stdout);
						nimln(39, "factorizar.nim");
						n0 = m0;
					} LA5: ;
				}
				nimln(40, "factorizar.nim");
				{
					if (!(((NI) 0) < e0)) goto LA11;
					nimln(41, "factorizar.nim");
					p0.Field0 = d_C1849bXpr8Pdh29cb9aQLE3vA;
					nimln(42, "factorizar.nim");
					p0.Field1 = e0;
					nimln(43, "factorizar.nim");
					factorsseq0 = (TY_8Np6tlClE5az1CyqZdN19bQ*) incrSeqV2(&(factorsseq0)->Sup, sizeof(TY_1v9bKyksXWMsm0vNwmZ4EuQ));
					factorsseq0->data[factorsseq0->Sup.len] = p0;
					++factorsseq0->Sup.len;
				}
				LA11: ;
				nimln(1908, "system.nim");
				T_Cp3TFfIqQo1kvLGjPaz3VA_10 = addInt(res_9abQT5z83KHZNmrNbTymbXg, ((NI) 1));
				res_9abQT5z83KHZNmrNbTymbXg = (NI)(T_Cp3TFfIqQo1kvLGjPaz3VA_10);
			} LA3: ;
		}
	}
	nimln(44, "factorizar.nim");
	genericSeqAssign((&result0), factorsseq0, (&NTI_8Np6tlClE5az1CyqZdN19bQ));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(void, writeline_rBQVO3cm3BhnA9aEFD7PG6Qfactorizar)(FILE* f0, NimStringDesc** x0, NI x0Len0) {
	nimfr("writeLine", "sysio.nim")
	{
		NimStringDesc* i_kSboRGYz9bWc0rf2v8AlLGQ;
		NI i_kSboRGYz9bWc0rf2v8AlLGQ_2;
		i_kSboRGYz9bWc0rf2v8AlLGQ = (NimStringDesc*)0;
		nimln(1999, "system.nim");
		i_kSboRGYz9bWc0rf2v8AlLGQ_2 = ((NI) 0);
		{
			nimln(2000, "system.nim");
			while (1) {
				nimln(1999, "system.nim");
				nimln(235, "sysio.nim");
				if (!(i_kSboRGYz9bWc0rf2v8AlLGQ_2 < x0Len0)) goto LA3;
				nimln(2001, "system.nim");
				i_kSboRGYz9bWc0rf2v8AlLGQ = x0[i_kSboRGYz9bWc0rf2v8AlLGQ_2];
				nimln(236, "sysio.nim");
				write_c4mGyJBvK73pdM22jiweKQ(f0, i_kSboRGYz9bWc0rf2v8AlLGQ);
				nimln(1999, "system.nim");
				i_kSboRGYz9bWc0rf2v8AlLGQ_2 += ((NI) 1);
			} LA3: ;
		}
	}
	nimln(237, "sysio.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f0, ((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_11));
	popFrame();
}

N_NIMCALL(void, prettyfactorization_9bKmnnny2qFitg44gLo9c16g)(TY_8Np6tlClE5az1CyqZdN19bQ* factorsseq0) {
	NIM_BOOL alreadyprinted0;
	nimfr("pretty_factorization", "factorizar.nim")
	nimln(48, "factorizar.nim");
	alreadyprinted0 = NIM_FALSE;
	nimln(49, "factorizar.nim");
	{
		if (!((factorsseq0 ? factorsseq0->Sup.len : 0) == ((NI) 0))) goto LA3;
		nimln(50, "factorizar.nim");
		write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_12));
	}
	goto LA1;
	LA3: ;
	{
		{
			TY_1v9bKyksXWMsm0vNwmZ4EuQ p_qdpKg9cKvHdZJCNtG11FiRA;
			NI i_JM0sbaPFETXATDRDVz9brmg;
			NI L_085PZADdfHW2jmTo5Dw9aBg;
			memset((void*)(&p_qdpKg9cKvHdZJCNtG11FiRA), 0, sizeof(p_qdpKg9cKvHdZJCNtG11FiRA));
			nimln(3497, "system.nim");
			i_JM0sbaPFETXATDRDVz9brmg = ((NI) 0);
			nimln(3498, "system.nim");
			nimln(52, "factorizar.nim");
			L_085PZADdfHW2jmTo5Dw9aBg = (factorsseq0 ? factorsseq0->Sup.len : 0);
			{
				nimln(3499, "system.nim");
				while (1) {
					TY_24KAM9afIUgUaqBaEBB6r9bg LOC13;
					NI T_Cp3TFfIqQo1kvLGjPaz3VA_14;
					nimln(3497, "system.nim");
					if (!(i_JM0sbaPFETXATDRDVz9brmg < L_085PZADdfHW2jmTo5Dw9aBg)) goto LA8;
					nimln(3500, "system.nim");
					if ((NU)(i_JM0sbaPFETXATDRDVz9brmg) >= (NU)(factorsseq0->Sup.len)) raiseIndexError();
					p_qdpKg9cKvHdZJCNtG11FiRA = factorsseq0->data[i_JM0sbaPFETXATDRDVz9brmg];
					nimln(53, "factorizar.nim");
					{
						if (!alreadyprinted0) goto LA11;
						nimln(54, "factorizar.nim");
						write_c4mGyJBvK73pdM22jiweKQ(stdout, ((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_9));
					}
					LA11: ;
					nimln(55, "factorizar.nim");
					memset((void*)LOC13, 0, sizeof(LOC13));
					LOC13[0] = nimIntToStr(p_qdpKg9cKvHdZJCNtG11FiRA.Field0);
					LOC13[1] = copyString(((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_13));
					LOC13[2] = nimIntToStr(p_qdpKg9cKvHdZJCNtG11FiRA.Field1);
					write_OG3BP9aaTiau0tBdonibGTg(stdout, LOC13, 3);
					nimln(56, "factorizar.nim");
					alreadyprinted0 = NIM_TRUE;
					nimln(3497, "system.nim");
					T_Cp3TFfIqQo1kvLGjPaz3VA_14 = addInt(i_JM0sbaPFETXATDRDVz9brmg, ((NI) 1));
					i_JM0sbaPFETXATDRDVz9brmg = (NI)(T_Cp3TFfIqQo1kvLGjPaz3VA_14);
					nimln(3502, "system.nim");
					{
						nimln(52, "factorizar.nim");
						if (!!(((factorsseq0 ? factorsseq0->Sup.len : 0) == L_085PZADdfHW2jmTo5Dw9aBg))) goto LA16;
						nimln(3502, "system.nim");
						failedassertimpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_15));
					}
					LA16: ;
				} LA8: ;
			}
		}
	}
	LA1: ;
	nimln(57, "factorizar.nim");
	writeline_rBQVO3cm3BhnA9aEFD7PG6Qfactorizar(stdout, T_Cp3TFfIqQo1kvLGjPaz3VA_16, 1);
	popFrame();
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(220, "gc.nim");
	addzct_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(280, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(280, "gc.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(281, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src0);
		nimln(282, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(283, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(283, "gc.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(284, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest0));
		nimln(285, "gc.nim");
		{
			(*c0).refcount -= ((NI) 8);
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(286, "gc.nim");
			rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(287, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals0) {
	setStackBottom(locals0);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	factorizarDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NimStringDesc* LOC1;
	nimfr("factorizar", "factorizar.nim")
nimRegisterGlobalMarker(T_Cp3TFfIqQo1kvLGjPaz3VA_3);
nimRegisterGlobalMarker(T_Cp3TFfIqQo1kvLGjPaz3VA_4);
	nimln(59, "factorizar.nim");
	printf("%s\012", ((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_18)? (((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_18))->data:"nil");
	fflush(stdout);
	nimln(60, "factorizar.nim");
	asgnRefNoCycle((void**) (&s_YwfZBocky9bQVtUWcozCTrg), readline_fPRnXwDTqtynUYGl4OixAg(stdin));
	nimln(61, "factorizar.nim");
	numero_0pcR4K1CUgJaGm61CY7rgg = nsuParseInt(s_YwfZBocky9bQVtUWcozCTrg);
	nimln(62, "factorizar.nim");
	LOC1 = (NimStringDesc*)0;
	LOC1 = nimIntToStr(numero_0pcR4K1CUgJaGm61CY7rgg);
	printf("%s%s\012", ((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_19)? (((NimStringDesc*) &T_Cp3TFfIqQo1kvLGjPaz3VA_19))->data:"nil", LOC1? (LOC1)->data:"nil");
	fflush(stdout);
	nimln(63, "factorizar.nim");
	asgnRefNoCycle((void**) (&factorsseq_AN3HbB3vvESZC0wn9chyo7A), factorize_j9cKmPt8LHHuq9awLaHwEVUQ(numero_0pcR4K1CUgJaGm61CY7rgg));
	nimln(64, "factorizar.nim");
	prettyfactorization_9bKmnnny2qFitg44gLo9c16g(factorsseq_AN3HbB3vvESZC0wn9chyo7A);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, factorizarDatInit000)(void) {
static TNimNode* T_Cp3TFfIqQo1kvLGjPaz3VA_2[2];
static TNimNode T_Cp3TFfIqQo1kvLGjPaz3VA_0[3];
NTI_1v9bKyksXWMsm0vNwmZ4EuQ.size = sizeof(TY_1v9bKyksXWMsm0vNwmZ4EuQ);
NTI_1v9bKyksXWMsm0vNwmZ4EuQ.kind = 18;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ.base = 0;
NTI_1v9bKyksXWMsm0vNwmZ4EuQ.flags = 3;
T_Cp3TFfIqQo1kvLGjPaz3VA_2[0] = &T_Cp3TFfIqQo1kvLGjPaz3VA_0[1];
T_Cp3TFfIqQo1kvLGjPaz3VA_0[1].kind = 1;
T_Cp3TFfIqQo1kvLGjPaz3VA_0[1].offset = offsetof(TY_1v9bKyksXWMsm0vNwmZ4EuQ, Field0);
T_Cp3TFfIqQo1kvLGjPaz3VA_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_Cp3TFfIqQo1kvLGjPaz3VA_0[1].name = "Field0";
T_Cp3TFfIqQo1kvLGjPaz3VA_2[1] = &T_Cp3TFfIqQo1kvLGjPaz3VA_0[2];
T_Cp3TFfIqQo1kvLGjPaz3VA_0[2].kind = 1;
T_Cp3TFfIqQo1kvLGjPaz3VA_0[2].offset = offsetof(TY_1v9bKyksXWMsm0vNwmZ4EuQ, Field1);
T_Cp3TFfIqQo1kvLGjPaz3VA_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_Cp3TFfIqQo1kvLGjPaz3VA_0[2].name = "Field1";
T_Cp3TFfIqQo1kvLGjPaz3VA_0[0].len = 2; T_Cp3TFfIqQo1kvLGjPaz3VA_0[0].kind = 2; T_Cp3TFfIqQo1kvLGjPaz3VA_0[0].sons = &T_Cp3TFfIqQo1kvLGjPaz3VA_2[0];
NTI_1v9bKyksXWMsm0vNwmZ4EuQ.node = &T_Cp3TFfIqQo1kvLGjPaz3VA_0[0];
NTI_8Np6tlClE5az1CyqZdN19bQ.size = sizeof(TY_8Np6tlClE5az1CyqZdN19bQ*);
NTI_8Np6tlClE5az1CyqZdN19bQ.kind = 24;
NTI_8Np6tlClE5az1CyqZdN19bQ.base = (&NTI_1v9bKyksXWMsm0vNwmZ4EuQ);
NTI_8Np6tlClE5az1CyqZdN19bQ.flags = 2;
NTI_8Np6tlClE5az1CyqZdN19bQ.marker = Marker_TY_8Np6tlClE5az1CyqZdN19bQ;
}

